dependencies:
- name: postgresql
  version: 8.6.4
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: redis
  version: 10.5.3
  repository: https://kubernetes-charts.storage.googleapis.com/
