image: $CONTAINER_RELEASE_IMAGE

stages:
  - build
  - lint
  - test
  - deploy
  - tag_latest

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  POSTGRES_PASSWORD: password
  POSTGRES_DB: root
  POSTGRES_USER: root
  DATABASE_URL: postgres://root:password@postgres/root
  GIT_STRATEGY: none

build:
  stage: build
  image: docker:latest
  variables:
    GIT_STRATEGY: clone
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE
    - docker build --cache-from $CI_REGISTRY_IMAGE -t $CONTAINER_RELEASE_IMAGE .
    - docker push $CONTAINER_RELEASE_IMAGE

helm_lint:
  stage: lint
  image: dtzar/helm-kubectl
  variables:
    GIT_STRATEGY: clone
  only:
    - master
  script:
    - helm lint -f values.yaml cmc/

eslint:
  stage: lint
  script:
    - cd /app
    - yarn eslint

rubocop:
  stage: lint
  script:
    - cd /app
    - rubocop

detect_code_problems:
  stage: lint
  services:
    - postgres:latest
  artifacts:
    paths:
      - rubycritic
    expire_in: 30 days
  script:
    - cd /app
    - rubycritic app/ lib/ -s 97.00
    - FAIL_ON_ERROR=1 DATABASE_URL=postgres://root:password@postgres/root rake traceroute
    - mv /app/tmp/rubycritic $CI_PROJECT_DIR

rspec:
  stage: test
  services:
    - postgres:latest
  variables:
    COVERAGE: "true"
  artifacts:
    paths:
      - coverage/
    expire_in: 30 days
  script:
    - cd /app
    - rspec
    - mv /app/coverage/ $CI_PROJECT_DIR

mocha:
  stage: test
  script:
    - cd /app
    - yarn test

cucumber:
  stage: test
  services:
    - postgres:latest
    - name: selenium/standalone-chrome-debug:latest
      alias: selenium
  variables:
    POSTGRES_PASSWORD: password
    POSTGRES_DB: root
    POSTGRES_USER: root
    SELENIUM_HOST: selenium
    SELENIUM_PORT: 4444
    TEST_PORT: 3001
    RAILS_ENV: test
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
  script:
    - cd /app
    - cucumber

deploy:
  stage: deploy
  image: aronwolf/helm-doctl
  allow_failure: true
  variables:
    GIT_STRATEGY: clone
  environment:
    name: production
    url: http://cost-manager.com
  script:
    - doctl kubernetes cluster kubeconfig save webcloudpower
    - helm init --upgrade
    - helm upgrade cmc-production cmc --install --wait
        -f values.yaml
        --set image.tag=$CI_COMMIT_SHA
        --set postgresql.postgresqlPassword=$DB_PASSWORD
        --set admin_password=$ADMIN_PASSWORD
        --set webAws.key=$WEB_AWS_KEY
        --set webAws.secret=$WEB_AWS_SECRET
        --namespace cmc-production
  only:
    - master

tag_latest:
  stage: tag_latest
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker pull $CONTAINER_RELEASE_IMAGE
    - docker tag $CONTAINER_RELEASE_IMAGE $CI_REGISTRY_IMAGE:latest
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

pages:
  stage: deploy
  image: alpine:latest
  dependencies:
    - rspec
    - detect_code_problems
  script:
    - mv coverage/ public/
    - mv rubycritic public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
  except:
    - schedules
  except:
    - schedules
