stages:
  - lint
  - test
  - build
  - deploy

variables:
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest
  POSTGRES_PASSWORD: password
  POSTGRES_DB: root
  POSTGRES_USER: root
  DATABASE_URL: postgres://root:password@postgres/root


gitlint:
  stage: lint
  image: python:3.7.0a4-alpine3.7
  script:
    - apk update
    - apk add git
    - pip install gitlint
    - git log -1 --pretty=%B | gitlint

helm_lint:
  stage: lint
  image: dtzar/helm-kubectl
  only:
    - master
  script:
    - helm lint -f values.yaml cmc/

eslint:
  stage: lint
  image: registry.gitlab.com/cmc_system/cmc/cmc:test
  script:
    - ln -s /root/node_modules node_modules
    - yarn install
    - yarn eslint

rubocop:
  stage: lint
  image: registry.gitlab.com/cmc_system/cmc/cmc:test
  script:
    - ln -s /root/node_modules node_modules
    - bundle install
    - rubocop

detect_code_problems:
  stage: lint
  image: registry.gitlab.com/cmc_system/cmc/cmc:test
  services:
    - postgres:latest
  artifacts:
    paths:
      - tmp/rubycritic
    expire_in: 30 days
  script:
    - bundle install
    - rubycritic app/ lib/ -s 97.00
    - rails_best_practices -e "db/migrate"
    - FAIL_ON_ERROR=1 DATABASE_URL=postgres://root:password@postgres/root rake traceroute

rspec:
  stage: test
  image: registry.gitlab.com/cmc_system/cmc/cmc:test
  services:
    - postgres:latest
  variables:
    COVERAGE: "true"
  artifacts:
    paths:
      - coverage/
    expire_in: 30 days
  script:
    - bundle install
    - ln -s /root/node_modules node_modules
    - rspec

mocha:
  stage: test
  image: registry.gitlab.com/cmc_system/cmc/cmc:test
  script:
    - ln -s /root/node_modules node_modules
    - yarn install
    - yarn test

cucumber:
  stage: test
  image: registry.gitlab.com/cmc_system/cmc/cmc:test
  tags:
    - selenium
  services:
    - postgres:latest
    - selenium/standalone-chrome-debug:latest
  variables:
    POSTGRES_PASSWORD: password
    POSTGRES_DB: root
    POSTGRES_USER: root
    DATABASE_URL: postgres://root:password@localhost/root
    SELENIUM_HOST: localhost
    SELENIUM_PORT: 4444
    TEST_PORT: 3001
    RAILS_ENV: test
    TEST_HOST: lvh.me
    DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: 'true'
  script:
    - bundle install
    - ln -s /root/node_modules node_modules
    - yarn install
    - cucumber

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker tag $CONTAINER_RELEASE_IMAGE $CONTAINER_RELEASE_IMAGE_LATEST
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE_LATEST
  only:
    - master
  except:
    - schedules

build_test:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk update
    - apk add make
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make build_and_push_test_image
  only:
    - schedules

deploy:
  stage: deploy
  image: dtzar/helm-kubectl
  environment:
    name: production
    url: http://cost-manager.com
  script:
    - mkdir ~/.kube
    - echo $KUBE_CONFIG | base64 -d > ~/.kube/config
    - helm init --upgrade
    - export LOGS_COMAND="\$(kubectl get pods -l name=cmc-migrate-task | sed -n 2p | awk '{print \$1}')"
    - sleep 2 &&
      until kubectl logs $(eval echo $LOGS_COMAND) && kubectl logs -f $(eval echo $LOGS_COMAND); do
        sleep 0.2;
      done &
    - helm upgrade cmc-production cmc --install --wait
        - f values.yaml
        --set image.tag=$CI_COMMIT_SHA
        --set postgresql.postgresqlPassword=$DB_PASSWORD
        --set admin_password=$ADMIN_PASSWORD
  only:
    - master
  except:
    - schedules

pages:
  stage: deploy
  image: alpine:latest
  dependencies:
    - rspec
    - detect_code_problems
  script:
    - mv coverage/ public/
    - mv tmp/rubycritic public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master
  except:
    - schedules
  except:
    - schedules
