image: docker:latest
services:
  - docker:dind

stages:
  - build
  - test
  - release
  - deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/cmc_system/cmc/cmc:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/cmc_system/cmc/cmc:$CI_COMMIT_SHA

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t $CONTAINER_TEST_IMAGE .
    - docker push $CONTAINER_TEST_IMAGE

rspec:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run -d -e POSTGRES_USER='root' -e POSTGRES_PASSWORD='password' -e POSTGRES_DB='root' --name postgres postgres:latest
    - docker run -e DATABASE_URL='postgres://root:password@db/root' --link=postgres:db $CONTAINER_TEST_IMAGE rspec

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master

deploy:
  stage: deploy
  script:
    - 'which ssh-agent || ( apk update  && apk add openssh-client  )'
    - eval $(ssh-agent -s)
    - apk add bash
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - sed -i -e "/cmc:[0-9a-fA-F]+/cmc:$CONTAINER_RELEASE_IMAGE/g" cmc_deploy/web_deployment.yml
    - sed -i -e "/cmc:[0-9a-fA-F]+/cmc:$CONTAINER_RELEASE_IMAGE/g" cmc_deploy/migrate_job.yml
    - ssh root@aronwolf.tk "kubectl replace -f cmc_deploy/web_deployment.yml -record
    - ssh root@aronwolf.tk "kubectl apply -f cmc_deploy/migrate_job.yml --record
    - ssh root@aronwolf.tk "bash -c \"cd cmc_deploy; git commit -am 'deploy to image cmc:$CONTAINER_RELEASE_IMAGE'; git push origin\""
  only:
    - master
