stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_TEST_IMAGE: registry.gitlab.com/cmc_system/cmc/cmc:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: registry.gitlab.com/cmc_system/cmc/cmc:$CI_COMMIT_SHA
  CONTAINER_RELEASE_IMAGE_LATEST: registry.gitlab.com/cmc_system/cmc/cmc:latest

rspec:
  stage: test
  image: registry.gitlab.com/cmc_system/cmc/cmc:test
  services:
    - postgres:latest
  variables:
    POSTGRES_PASSWORD: password
    POSTGRES_DB: root
  script:
    - ./alphine_shared_install.sh
    - bundle install
    - yarn install
    - rspec

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CONTAINER_RELEASE_IMAGE .
    - docker tag $CONTAINER_RELEASE_IMAGE CONTAINER_RELEASE_IMAGE_LATEST
    - docker push $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE_LATEST
  only:
    - master

deploy:
  stage: deploy
  image: registry.gitlab.com/cmc_system/cmc/cmc:test
  script:
    - 'which ssh-agent || ( apk update  && apk add openssh-client  )'
    - eval $(ssh-agent -s)
    - apk add bash
    - bash -c 'ssh-add <(echo "$SSH_PRIVATE_KEY")'
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh root@aronwolf.tk 'sed -i -e "/cmc:[0-9a-fA-F]+/cmc:$CI_COMMIT_SHA/g" cmc_deploy/web_deployment.yml'
    - ssh root@aronwolf.tk 'sed -i -e "/cmc:[0-9a-fA-F]+/cmc:$CI_COMMIT_SHA/g" cmc_deploy/migrate_job.yml'
    - ssh root@aronwolf.tk "kubectl replace -f cmc_deploy/web_deployment.yml --record"
    - ssh root@aronwolf.tk "kubectl delete -f cmc_deploy/migrate_job.yml"
    - ssh root@aronwolf.tk "kubectl apply -f cmc_deploy/migrate_job.yml"
    - ssh root@aronwolf.tk "bash -c \"cd cmc_deploy; git commit -am 'deploy to image $CONTAINER_RELEASE_IMAGE'; git push origin\""
  only:
    - master
