image: docker:latest
services:
  - docker:dind
  - postgres:latest

stages:
  - build
  - test
  - release

variables:
  CONTAINER_TEST_IMAGE: cmc:$CI_COMMIT_REF_NAME
  CONTAINER_RELEASE_IMAGE: cmc:latest

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com

build:
  stage: build
  script:
    - docker build -t cmc_prebuild -f DockerfilePrebuild .
    - docker build -t cmc -f Dockerfile .
    - docker push $CONTAINER_TEST_IMAGE

rspec:
  stage: test
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker run $CONTAINER_TEST_IMAGE rspec

release-image:
  stage: release
  script:
    - docker pull $CONTAINER_TEST_IMAGE
    - docker tag $CONTAINER_TEST_IMAGE $CONTAINER_RELEASE_IMAGE
    - docker push $CONTAINER_RELEASE_IMAGE
  only:
    - master


