ignore_unreachable_actions:
- ^devise
- authenticate!$
- authenticate_for$
- ^knock
- user_tokens
- model_class
- per_page
- serializer
- collection_query
- operation
- action_mailbox/inbound_emails

ignore_unused_routes:
- ^devise
- user_tokens
- /sidekiq
- action_mailbox/inbound_emails
- google_calenders#create_callback
- google_calenders#notificatio
