version: '2.2'
services:
  app:
    image: $IMAGE
    extra_hosts:
      - db:$POSTGRES_IP
      - redis:$REDIS_IP
      - storage.lvh.me:$STORAGE_IP
      - mail_hog:$MAIL_HOG_IP
      - stripe_mock:$STRIPE_MOCK_IP
      - payment:$PAYMENT_IP
    dns: 8.8.8.8
    command:  sh -c "RAILS_ENV=production rails s -b '0.0.0.0'"
    volumes:
      - ./screenshots/:/app/screenshots/
    networks:
      default:
        aliases:
          - test-organization.lvh.me
          - lvh.me
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db/database
      - AWS_KEY=access_key
      - AWS_SECRET=secret_key
      - AWS_ENDPOINT=http://storage.lvh.me:9000
      - CAPYBARA_RUN_SERVER=false
      - TEST_PORT=3000
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - RAILS_SERVE_STATIC_FILES=true
      - SEEDS_FOLDER=development
      - PAYMENT_ENABLED=true
      - NO_RAISE_MAILER_ERRORS=true
      - REDIS_URL=redis://redis
      - TEST_HOST=lvh.me
      - SECRET_KEY_BASE=5d1ee3590cdac32f527d1c4c835578859ecbd50ac1b03ff6d4689c19d732b5c9050ceb66d8b625cacadb1c1228095a7fd855933ce1881075a577e7cb8aea3432
      - MAILER_SMTP_DOMAIN=mail_hog
      - MAILER_PORT=1025 
      - DISABLE_DATABASE_ENVIRONMENT_CHECK=true
    ports:
      - "3000:3000"

  selenium:
    image: selenium/standalone-chrome-debug
    ports:
      - "4444:4444"
      - "5901:5900"
