version: '2.2'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=root
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports: 
      - 6432:5432

  webpack:
    image: registry.gitlab.com/cmc_system/cmc:latest
    command: bash -c "bin/install.sh; bin/webpack-dev-server"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    ports:
      - "3035:3035"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

  app:
    image: registry.gitlab.com/cmc_system/cmc:latest
    build: .
    stdin_open: true
    tty: true
    environment:
      - DB_PASSWORD=password
      - DB_HOST=db
      - BUNDLE_BIN=false
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
      - TEST_PORT=3001
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - WEBPACKER_DEV_SERVER_HOST=webpack
    command:  /bin/sh -c "bin/install.sh; rm -r tmp/pids; rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    depends_on:
      - db
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: 1g

volumes:
  bundle:
    driver: local
  db_volume:
