version: '3.0'
services:
  db:
    image: postgres:11
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports: 
      - 6432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 30

  stripe_mock:
    image: registry.gitlab.com/web_utils/mockserver-docker:latest
    volumes:
      - ./stripe_mocks:/mocks
    ports:
      - "8080:8080"

  payment:
    image: registry.gitlab.com/cmc_system/cmc_payment
    ports:
      - "5000:4000"
    depends_on:
      - db
      - stripe_mock

  storage:
    image: minio/minio
    entrypoint: sh
    command: -c 'mkdir -p /data/cmc; /usr/bin/minio server /data'
    networks:
      default:
        aliases:
          - storage.lvh.me
    environment:
      - MINIO_ACCESS_KEY=access_key
      - MINIO_SECRET_KEY=secret_key
    ports:
      - "9000:9000"
    volumes:
      - storage_volume:/data

  webpack:
    image: registry.gitlab.com/cmc_system/cmc:$TAG
    command: bash -c "bin/install.sh; bin/webpack-dev-server"
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    ports:
      - "3035:3035"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle

  app:
    image: registry.gitlab.com/cmc_system/cmc:$TAG
    build: .
    stdin_open: true
    tty: true
    environment:
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - BUNDLE_BIN=false
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
      - TEST_PORT=3001
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - WEBPACKER_DEV_SERVER_HOST=webpack
      - AWS_KEY=access_key
      - AWS_SECRET=secret_key
      - AWS_ENDPOINT=http://storage.lvh.me:9000
    command:  /bin/sh -c "bin/install.sh; rm -r tmp/pids; rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - .:/app:cached
      - bundle:/usr/local/bundle:cached
    depends_on:
      - db
      - selenium
      - storage
      - payment

  selenium:
    image: selenium/standalone-chrome-debug:$TAG
    ports:
      - "4444:4444"
      - "5901:5900"
    shm_size: 1g

volumes:
  bundle:
  db_volume:
  storage_volume:
