version: '2.2'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=root
    volumes:
      - db_volume:/var/lib/postgresql/data

  webpack:
    image: cmc
    command: webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    ports:
      - "3035:3035"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules

  app:
    image: cmc
    build:
      dockerfile: DockerfileDevelop
      context: .
      args:
        - UID=${uid}
        - GID=${gid}
    environment:
      - DB_PASSWORD=password
      - DB_HOST=db
      - BUNDLE_BIN=false
      - WEBPACKER_DEV_SERVER_HOST=webpack
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=app
      - TEST_PORT=3001
    command:  /bin/sh -c "rm -r tmp/pids; rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
      - "4444:4444"
      - "5900:5900"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - ~/.gitconfig:/root/.gitconfig
    depends_on:
      - db
      - webpack

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: 2g
    logging:
      driver: none

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  db_volume:
    driver: local
