version: '2.2'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=root
    volumes:
      - db_volume:/var/lib/postgresql/data

  webpack:
    image: cmc
    command: webpack-dev-server
    environment:
      - WEBPACKER_DEV_SERVER_HOST=webpack
    ports:
      - "3035:3035"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules

  web:
    image: cmc
    build:
      dockerfile: DockerfileDevelop
      context: .
    environment:
      - DATABASE_URL=postgres://root:password@db/root
      - BUNDLE_BIN=false
      - WEBPACKER_DEV_SERVER_HOST=webpack
    command:  /bin/sh -c "rm -r tmp/pids; rails s -b '0.0.0.0'"
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
    depends_on:
      - db
      - webpack

  db_test:
    image: labianchin/docker-postgres-for-testing
    logging:
      driver: none
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=root

  test:
    image: cmc
    build:
      dockerfile: DockerfileDevelop
      context: .
    environment:
      - DATABASE_URL=postgres://root:password@db%5Ftest/root
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
      - RAILS_ENV=test
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=test
      - TEST_PORT=3001
      - BUNDLE_BIN=false
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      - ~/.ssh:/root/.ssh
    depends_on:
      - db_test
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: 2g
    logging:
      driver: none

volumes:
  bundle:
    driver: local
  node_modules:
    driver: local
  db_volume:
    driver: local
