version: '2.2'
services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=root
    volumes:
      - db_volume:/var/lib/postgresql/data
    ports: 
      - 6432:5432

  app:
    image: cmc
    networks:
      default:
        aliases:
          - test-organization.app.local
          - app.local
    build:
      dockerfile: DockerfileDevelop
      context: .
      args:
        - UID=${uid}
        - GID=${gid}
        - USER_NAME=${USER}
    environment:
      - DB_PASSWORD=password
      - DB_HOST=db
      - BUNDLE_BIN=false
      - DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true
      - SELENIUM_HOST=selenium
      - SELENIUM_PORT=4444
      - TEST_APP_HOST=app.local
      - TEST_HOST=app.local
      - TEST_PORT=3001
    command:  /bin/sh -c "rm -r tmp/pids; rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
      - "3035:3035"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ~/.ssh:/user/.ssh
      - ~/.gitconfig:/user/.gitconfig
    depends_on:
      - db
      - selenium

  selenium:
    image: selenium/standalone-chrome-debug:latest
    ports:
      - "4444:4444"
      - "5900:5900"
    shm_size: 1g

volumes:
  bundle:
    driver: local
  db_volume:
    driver: local
