multiTenant: true
installJobDelay: 60
ingress:
  enabled: true
  url: cost-manager.com
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  tls:
    - secretName: cost-manager-tls
      hosts:
        - "*.cost-manager.com"
        - "cost-manager.com"
webAws:
  enabled: true
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  directory: webcloudpower/cmc-production
