multiTenant: true
installJobDelay: 60
url: ticktensio.com
deprecatedUrl: cost-manager.com
postgresql:
  postgresqlUsername: root
  master:
    podAnnotations:
      backup.velero.io/backup-volumes: data
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: true
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
  tls:
    - secretName: cost-manager-tls
      hosts:
        - "*.cost-manager.com"
        - "cost-manager.com"
        - "*.ticktensio.com"
        - "ticktensio.com"
webAws:
  enabled: true
  region: fra1
  endpoint: https://fra1.digitaloceanspaces.com
  directory: webcloudpower/cmc-production

payment:
  enabled: true
  host: https://payment.ticktensio.com

mailer:
  smtp_domain: smtp.migadu.com 
  domain: ticktensio.com 
  user_name: info@ticktensio.com
  port: 587
  password:
