apiVersion: v1
kind: Service
metadata:
  name: cmc-database
  labels:
    name: cmc-database
spec:
  externalIPs:
    - {{ .Values.external_ip }}
  ports:
    - port: 5432
  selector:
    name: cmc-database
