apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cmc-database
  labels:
    name: cmc-database
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: cmc-database
    spec:
      containers:
        - image: postgres:latest
          name: cmc-database
          env:
            - name: POSTGRES_DB
              value: database
            - name: POSTGRES_USER
              value: root
            - name: POSTGRES_PASSWORD
              value: {{ .Values.db_password }}
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: cmc-database
          volumeMounts:
            - name: cmc-database-volume
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: cmc-database-volume
          persistentVolumeClaim:
            claimName: cmc-db-pvc
