kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-front
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-front
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9001
