{{ if "google.createSecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-google
  labels:
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  clientId: {{ .Values.google.clientId | b64enc | quote }}
  calenderSecret: {{ .Values.google.calenderSecret | b64enc | quote }}
{{ end }}
