apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cmc-ingress
  annotations:
    certmanager.k8s.io/cluster-issuer: {{ .Values.cluster_issuer }} 
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
        - path: /
          backend:
            serviceName: cmc-service
            servicePort: 80
        - path: /
          backend:
            serviceName: cmc-database
            servicePort: 5432
  - host: "*.{{ .Values.url }}"
    http:
      paths:
        - path: /
          backend:
            serviceName: cmc-service
            servicePort: 80

  tls:
    - hosts:
        - "*.{{ .Values.url }}"
        - "{{ .Values.url }}"
      secretName: cost-manager-tls

