apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cmc-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: {{ .Values.url }}
    http:
      paths:
        - path: /
          backend:
            serviceName: cmc-service
            servicePort: 80

