apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    {{- range $key, $value := .Values.ingress.annotations }}
      {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.url }}
      http:
        paths:
          - path: /(api/.*|users.*|registrations.*|admin_area.*|favicon.ico|sidekiq/.*|administration/dashboard|packs/.*)?$
            backend:
              serviceName: {{ .Release.Name }}-back
              servicePort: 80
          - path: /.*
            backend:
              serviceName: {{ .Release.Name }}-front
              servicePort: 80
    {{- if .Values.multiTenant }}
    - host: "*.{{ .Values.url }}"
      http:
        paths:
          - path: /(api/.*|users.*|registrations.*|admin_area.*|favicon.ico|sidekiq/.*|administration/dashboard|packs/.*)?
            backend:
              serviceName: {{ .Release.Name }}-service
              servicePort: 80
    {{- end }}

  {{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end -}}
