{{ if "mailer.createSecret" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mailer
  labels:
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  password: {{ .Values.mailer.password | b64enc | quote }}
  smtpDomain: {{ .Values.mailer.smtp_domain | b64enc | quote }}
  domain: {{ .Values.mailer.domain | b64enc | quote }}
  userName: {{ .Values.mailer.user_name | b64enc | quote }}
  port: {{ .Values.mailer.port | b64enc | quote }}
{{ end }}
