{{ if "payment.secret.create" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-payment
  labels:
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
type: Opaque
data:
  PAYMENT_TOKEN: {{ .Values.payment.secret.token | b64enc | quote }}
{{ end }}
