kind: Service
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-web
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
