apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-web
  labels:
    name: {{ .Release.Name }}-web
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          env:
            - name: DATABASE_URL
              value: 'postgres://{{ .Values.postgresql.postgresqlUsername }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql/{{ .Values.postgresql.postgresqlDatabase }}'
            - name: SECRET_KEY_BASE
              value: '{{ .Values.webDeployment.secretKeyBase }}'
            - name: RAILS_ENV
              value: '{{ .Values.webDeployment.enviroment }}'
            - name: MULTI_TENANT
              value: '{{ .Values.multiTenant }}'
            - name: SENTRY_DSN
              value: '{{ .Values.webDeployment.sentryDsn }}'
            - name: ADMIN_PASSWORD
              value: '{{ .Values.admin_password }}'
            - name: AWS_ENABLED
              value: '{{ .Values.webAws.enabled }}'
            - name: AWS_KEY
              value: '{{ .Values.webAws.key }}'
            - name: AWS_SECRET
              value: '{{ .Values.webAws.secret }}'
            - name: AWS_REGION
              value: '{{ .Values.webAws.region }}'
            - name: AWS_ENDPOINT
              value: '{{ .Values.webAws.endpoint }}'
            - name: AWS_DIRECTORY
              value: '{{ .Values.webAws.directory }}'
            - name: PAYMENT_HOST
              value: '{{ .Values.payment.host }}'
            - name: HOST
              value: '{{ .Values.url }}'
            - name: MAILER_SMTP_DOMAIN 
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mailer
                  key: smtpDomain
            - name: MAILER_DOMAIN 
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mailer
                  key: domain
            - name: MAILER_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mailer
                  key: userName
            - name: MAILER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mailer
                  key: password
            - name: MAILER_PORT
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mailer
                  key: port
            - name: PAYMENT_ENABLED
              value: '{{ .Values.payment.enabled }}'
            - name: REDIS_URL
              value: 'redis://{{ .Release.Name }}-redis-master'
            - name: RAILS_LOG_TO_STDOUT
              value: 'true'
              
          volumeMounts:
            {{- if .Values.webPersistence.enabled }}
            - name: files
              mountPath: /app/uploads
            {{- end }}
            - mountPath: /assets
              name: assets
          lifecycle:
            postStart:
              exec:
                command:
                  - sh
                  - -c
                  - "cp -r /app/public/* /assets"
          livenessProbe:
            httpGet:
              path: /api/v1/health_check
              port: http
          readinessProbe:
            httpGet:
              path: /api/v1/health_check
              port: http

        - image: nginx:1.14-alpine
          name: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /assets
              name: assets
              readOnly: true
            - mountPath: /etc/nginx/nginx.conf
              name: nginx-conf
              subPath: nginx.conf
              readOnly: true

      volumes:
        {{- if .Values.webPersistence.enabled }}
        - name: files
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-web-pvc
        {{- end }}
        - name: nginx-conf
          configMap:
            name: {{ .Release.Name }}-nginx-conf
            items:
              - key: nginx.conf
                path: nginx.conf
        - name: assets
          emptyDir: {}
