apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    name: {{ .Release.Name }}-worker
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-web
    spec:
      containers:
        - name: web
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/sh","-c"]
          args: ["bundle exec sidekiq"]
          ports:
            - containerPort: 3000
          env:
            - name: DATABASE_URL
              value: 'postgres://{{ .Values.postgresql.postgresqlUser }}:{{ .Values.postgresql.postgresqlPassword }}@{{ .Release.Name }}-postgresql/{{ .Values.postgresql.postgresqlDatabase }}'
            - name: SECRET_KEY_BASE
              value: '{{ .Values.webDeployment.secretKeyBase }}'
            - name: RAILS_ENV
              value: '{{ .Values.webDeployment.enviroment }}'
            - name: MULTI_TENANT
              value: '{{ .Values.multiTenant }}'
            - name: SENTRY_DSN
              value: '{{ .Values.webDeployment.sentryDsn }}'
            - name: ADMIN_PASSWORD
              value: '{{ .Values.admin_password }}'
            - name: AWS_ENABLED
              value: '{{ .Values.webAws.enabled }}'
            - name: AWS_KEY
              value: '{{ .Values.webAws.key }}'
            - name: AWS_SECRET
              value: '{{ .Values.webAws.secret }}'
            - name: AWS_REGION
              value: '{{ .Values.webAws.region }}'
            - name: AWS_ENDPOINT
              value: '{{ .Values.webAws.endpoint }}'
            - name: AWS_DIRECTORY
              value: '{{ .Values.webAws.directory }}'
            - name: PAYMENT_HOST
              value: '{{ .Values.payment.host }}'
            - name: HOST
              value: '{{ .Values.url }}'
            - name: MAILER_SMTP_DOMAIN 
              value: '{{ .Values.mailer.smtp_domain }}'
            - name: MAILER_DOMAIN 
              value: '{{ .Values.mailer.domain }}'
            - name: MAILER_USER_NAME
              value: '{{ .Values.mailer.user_name }}'
            - name: MAILER_PASSWORD
              value: '{{ .Values.mailer.password }}' 
            - name: MAILER_PORT
              value: '{{ .Values.mailer.port }}'
            - name: PAYMENT_ENABLED
              value: '{{ .Values.payment.enabled }}'
            - name: REDIS_URL
              value: redis://{{ .Release.Name }}-redis-master
