development:
  adapter: postgresql
  encoding: unicode
  database: cmc_development
  pool: 5
  username: <%= ENV["DB_USER"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "localhost" %>

test:
  adapter: postgresql
  encoding: unicode
  database: cmc_test
  pool: 5
  username: <%= ENV["DB_USER"] || "postgres" %>
  password: <%= ENV["DB_PASSWORD"] %>
  host: <%= ENV["DB_HOST"] || "localhost" %>

