multi_tenant: <%= ENV["MULTI_TENANT"] || true%>
host: <%= ENV["HOST"] || "lvh.me:3000" %>
admin_password: <%= ENV["ADMIN_PASSWORD"] || "testtest" %>
test_host: <%= ENV["TEST_HOST"] || "localhost" %> 
test_port: <%= ENV["TEST_PORT"] || "3001" %>
stripe_public_key: <%= ENV["STRIPE_PUBLIC_KEY"] || "pk_test_jnjnLmEpUo9tbTIEjKKGPr62007x2iQKkM" %>
payment:
  enabled: <%= ENV["PAYMENT_ENABLED"] %>
  host: <%= ENV["PAYMENT_HOST"] || "http://payment:4000" %>
  headers:
    "Authorization": Basic YWRtaW46dGVzdHRlc3Q=
    "Content-Type": application/json
redis_url: <%= ENV["REDIS_URL"]  %>
organization_blacklist:
  - about
  - payment 
google_calender:
  web_hook: <%= ENV["GOOGLE_CALENDER_WEB_HOOK"] %>
  client_id: <%= ENV["GOOGLE_CALENDER_CLIENT_ID"] || "test" %>
  client_secret: <%= ENV["GOOGLE_CALENDER_CLIENT_SECRET"] || "test" %>
  authorization_uri: 'https://accounts.google.com/o/oauth2/auth'
  token_credential_uri: 'https://accounts.google.com/o/oauth2/token'
devise_header_js: |
  <%= ENV["DEVISE_HEADER_JS"].to_s.gsub("\n", "\n  ") %>
administration_header_js: |
  <%= ENV["ADMINISTRATION_HEADER_JS"].to_s.gsub("\n", "\n  ") %>
recaptcha_enabled: <%= ENV["RECAPTCHA_ENABLED"] %>
recaptcha_ignore_key: <%= ENV["RECAPTCHA_IGNORE_KEY"] %>
sentry_dsn: <%= ENV["SENTRY_DSN"] %>
