multi_tenant: <%= ENV["MULTI_TENANT"] || true%>
host: <%= ENV["HOST"] || "lvh.me:3000" %>
admin_password: <%= ENV["ADMIN_PASSWORD"] || "testtest" %>
test_host: <%= ENV["TEST_HOST"] || "localhost" %> 
test_port: <%= ENV["TEST_PORT"] || "3001" %>
stripe_public_key: pk_test_jnjnLmEpUo9tbTIEjKKGPr62007x2iQKkM
payment:
  enabled: <%= ENV["PAYMENT_ENABLED"] %>
  host: <%= ENV["PAYMENT_HOST"] || "http://payment:4000" %>
  headers:
    "Authorization": Basic YWRtaW46dGVzdHRlc3Q=
    "Content-Type": application/json
redis_url: <%= ENV["REDIS_URL"]  %>
organization_blacklist:
  - about
  - payment 
