{{- if .Values.databaseService.externalIp }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-ext
  labels:
    name: {{ .Release.Name }}-db-ext
spec:
  {{- if .Values.databaseService.externalIp }}
  externalIPs:
    - {{ .Values.databaseService.externalIp }}
  {{- end }}
  ports:
    - port: 5432
  selector:
    app: postgresql
    release: {{ .Release.Name }}
    role: master
{{- end }}
