apiVersion: batch/v1
kind: Job
metadata:
  name: cmc-install-task
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: cmc-install-task
      labels:
        name: cmc-install-task
    spec:
      restartPolicy: Never
      containers:
        - name: cmc-install-task
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          command: ["/bin/sh","-c"]
          args: ["sleep {{ .Values.installJobDelay }}; rake db:schema:load; rake db:seed"]
          imagePullPolicy: "Always"
          env:
            - name: DATABASE_URL
              value: 'postgres://root:{{ .Values.databasePassword }}@cmc-database/database'
            - name: SECRET_KEY_BASE
              value: '{{ .Values.webDeployment.secretKeyBase }}'
            - name: RAILS_ENV
              value: '{{ .Values.webDeployment.enviroment }}'
            - name: MULTI_TENANT
              value: '{{ .Values.multiTenant }}'
            - name: SENTRY_DSN
              value: '{{ .Values.webDeployment.sentryDsn }}'
